[versions]
junit-jupiter = "5.9.2"
junit-platform-launcher = "1.9.2"
utils = "1.0"

[libraries]
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform-launcher" }
utils = { group = "de.dasbabypixel", name = "utils", version.ref = "utils" }

[plugins]

[bundles]

